server:
  port: 80

spring:
  datasource:
    username: user
    password: secret
    database: subscriptions
    host: ${SIMPLE_MUSIC_SUBSCRIPTIONS_STORAGE_HOST}
    port: ${SIMPLE_MUSIC_SUBSCRIPTIONS_STORAGE_PORT}
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.database}
  cloud:
    consul:
      enabled: true
      host: ${SIMPLE_MUSIC_REGISTRY_HOST}
      port: ${SIMPLE_MUSIC_REGISTRY_PORT}
      discovery:
        instanceId: ${spring.application.name}:${random.value}

security:
  service-id: subscriptions
  service-password: secret
  token-lifetime: 30
